DROP DATABASE IF EXISTS doings_done;

CREATE DATABASE doings_done
    DEFAULT CHARACTER SET utf8
    DEFAULT COLLATE utf8_general_ci;
USE doings_done;

CREATE TABLE user (
id INT AUTO_INCREMENT PRIMARY KEY UNIQUE,
reg_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
email CHAR(255) UNIQUE NOT NULL,
name CHAR(64) NOT NULL,
password VARCHAR(255) NOT NULL
);

CREATE TABLE project(
id INT AUTO_INCREMENT PRIMARY KEY UNIQUE,
name CHAR(255) UNIQUE NOT NULL,
user INT NOT NULL,
FOREIGN KEY (user) REFERENCES user(id)
);

CREATE TABLE task(
id INT PRIMARY KEY AUTO_INCREMENT UNIQUE,
task_crete TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
status TINYINT(1) DEFAULT 0,
title CHAR(255) NOT NULL,
file VARCHAR (255),
deadline TIMESTAMP,
user_id INT NOT NULL,
project_id INT NOT NULL,
FOREIGN KEY (user_id) REFERENCES user(id),
FOREIGN KEY (project_id) REFERENCES project(id)
);

